version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: finance_ai
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: 7wu394pejCknEgaFIXXkwbJp
    ports:
      - '5432:5432'
    volumes:
      - finance-ai-pg:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: postgresql://finance:7wu394pejCknEgaFIXXkwbJp@postgres:5432/finance_ai?schema=public
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: http://host.docker.internal:11434/v1
      OPENAI_MODEL: ${OPENAI_MODEL:-qwen2.5:3b}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - '4000:4000'
    env_file:
      - .env

volumes:
  finance-ai-pg:
    external: true
